### ISSUE TITLE
Would you please write in the README

### ISSUE THREAD

**Issue by mjm2017** [mubes/vidout#1]
Hi, 
Would you please write down how to compile the project? 
Could we use Eclipse with gcc on windows to compile the project?
thanks.

**Comment by mubes** [comment]
Hi there,

The project comes with a makefile and compiles with arm-gcc, so any 
mechanism (including Eclipse) that can support that will work. Here's 
what it looks like on Linux;

~/Develop/vidout$ make
  Compiling thirdparty/CMSIS/src/system_stm32f10x.c
  Compiling thirdparty/CMSIS/src/core_cm3.c
  Compiling vidout/rasterLine.c
  Compiling vidout/displayFile.c
  Compiling vidout/vidout.c
  Compiling app/main.c
  Assembling thirdparty/CMSIS/src/startup_stm32f10x_md.s
  Built Release version
    text       data        bss        dec        hex filename
    7704         40       3140      10884       2a84 ofiles/firmware.elf
~/Develop/vidout$

If you don't already have it, then you can download the toolchain from 
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm

...then you just need to burn that into the chip using whatever method 
you prefer ...in the ofiles/ directory you will find elf, bin and hex 
versions of the firmware as you prefer. Good luck.

Regards

DAVE
